Update call_thug.py
If you don't specify a configuration path for thug configuration files thugd failes because it can't find personalities.  ThugAPI by default looks for configuration_path but if that doesn't exist DOM/Personalities.py looks for the personalities directory in lib/python2.7/dist-packages/thug*/DOM.  

[2015-12-03 15:22:30,450: WARNING/Worker-4] [CRITICAL] Thug personalities not found! Exiting                                                                                   [92/1819]
[2015-12-03 15:22:30,468: ERROR/MainProcess] Task ThugD.thug_instances.thug[e4ec4b5c-3255-4f85-b61c-c6a4a1ce5d49] raised unexpected: WorkerLostError('Worker exited prematurely: exitcod
e 0.',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/billiard/pool.py", line 1175, in mark_as_worker_lost
    human_status(exitcode)),
WorkerLostError: Worker exited prematurely: exitcode 0.